config/routes.rb
PusherPresenceDemo::Application.routes.draw do
  resource :identity
  resources :messages
  match '/' => 'demo#index'
  match '/test' => 'demo#test_index'
  match '/pusher/auth' => 'pusher#auth'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  def index
    @identity = session[:identity]
    @use_local_js = false
  end

  def test_index
    @identity = session[:identity]
    @use_local_js = true
    render :index
  end
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
  def create  
    session[:identity] = {
      :email => params[:email],
      :gravatar => Gravatar.new(params[:email]).image_url
    }
    redirect_to :back 
  end
  
  def destroy
    session.delete(:identity)
    redirect_to :back
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    if EM.reactor_running?
      # Heroku apps run inside eventmachine so we can make API calls to pusher
      # outside the request-response cycle
      Pusher['presence-demo'].trigger_async('message', {
        :user_id => session[:user_id],
        :text => params[:text]
      })
    else
      Pusher['presence-demo'].trigger('message', {
        :user_id => session[:user_id],
        :text => params[:text]
      })
    end
    head :ok
  end
end

app/controllers/pusher_controller.rb
class PusherController < ApplicationController
  def auth
    # There's only one channel in this simple demo so we can hard code it
    raise "Unknown channel" unless params[:channel_name] == 'presence-demo'

    channel = Pusher['presence-demo']
    session[:user_id] ||= rand(1000000)

    if identity = session[:identity]
      response = channel.authenticate(params[:socket_id], {
        :user_id => session[:user_id],
        :user_info => {
          :gravatar => identity[:gravatar]
        }
      })
      render :json => response
    else
      # We're allowing anonymous users
      response = channel.authenticate(params[:socket_id], {
        :user_id => session[:user_id],
        :user_info => {}
      })
      render :json => response

      # You might alternatively want to deny them:
      # render :text => "Not authorized", :status => '403'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/demo/index.html.erb
<div id="header">
  <div id="fork-me"><a href="https://github.com/pusher/pusher-presence-demo">Fork me on GitHub</a></div>

  <a class="pusher" href="http://pusherapp.com/"><img alt="Pusher" src="/images/pusher.png"></a>

  <div id="controls">
    <% if @identity.nil? %>
      <h2>You are currently <em>anonymous</em></h2>
      <form action="/identity" id="email" method="POST">
        <input name="email" placeholder="Add your email to get a Gravatar" type="email">
        <input type="submit" value="Add my Gravatar">
      </form>
    <% else %>
      <h2>You're logged in as <em><%=h @identity[:email] %></em></h2>
      <%= form_for :identity, :url => identity_path, :html => { :method => :delete } do |f| %>
        <%= f.submit 'Remove my Gravatar' %>
      <% end %>
    <% end %>
    <form action="/messages" id="message" method="POST">
      <input name="text" placeholder="Say something">
      <input type="submit" value="Send">
    </form>
  </div>
</div>

<div id="presence"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pusher presence demo</title>
  <%= stylesheet_link_tag "application" %>

<% if @use_local_js %>
  <script src="http://localhost:5555/pusher.js"></script>
<% else %>
  <script src="<%= PUSHER_JS_DOMAIN %>/1.12.0/pusher.min.js"></script>
<% end %>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
  <%= javascript_include_tag "application" %>
<script>
  Pusher.host = '<%= PUSHER_SOCKET_HOST %>';
  Pusher.ws_port = <%= PUSHER_WS_PORT %>;

  var socket = new Pusher('<%= Pusher.key %>');
</script>
</head>
<body>
  <%= yield %>
</body>
</html>